# Generated by Django 4.0.5 on 2022-09-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchlike',
            name='dispatch',
        ),
        migrations.RemoveField(
            model_name='dispatchlike',
            name='order',
        ),
        migrations.RemoveField(
            model_name='dispatchprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dispatchprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='update_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Dispatch',
        ),
        migrations.DeleteModel(
            name='DispatchLike',
        ),
        migrations.DeleteModel(
            name='DispatchProfile',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='UserTransaction',
        ),
    ]
