# Generated by Django 4.0.5 on 2022-09-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dispatchlike_dispatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='info',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shop',
        ),
    ]
