# Generated by Django 4.0.5 on 2022-09-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='sgstst'),
            preserve_default=False,
        ),
    ]
